### ISSUE TITLE
Cron / scheduled work not running on agent.

### ISSUE THREAD

**Issue by r1ddl3m37h15** [OpenMake-Software/Meister#1]
Have a windows RBS running that won't run scheduled work.  Stopped working after a weekly reboot for security patching. 

Tried to cycle the agent several times now without successfully getting the cron part working. Made sure the JNT wasn't running. That normally helps. The schedules have always been a problem after booting but trial and error cycling normally fixes it.  Every once in a while restarting will bring is lots of missed runs. Flooding the queue with multiple copies of the same job.

Anyway, I need to get the cron part working again.

OpenMake Meister
Version: 7.40
Build ID: 2024

KB is on linux.

**Comment by sbtaylor15** [comment]
Attach the <install>/client/buildserver/logs/*.log files from the Windows RBS.

**Comment by r1ddl3m37h15** [comment]
Requested logs.


[RemoteBuildOut.log](https://github.com/OpenMake-Software/Meister/files/1391441/RemoteBuildOut.log)


RemoteBuildErr.log is empty and won't upload.

[RemoteBuildStartup.log](https://github.com/OpenMake-Software/Meister/files/1391433/RemoteBuildStartup.log)

**Comment by sbtaylor15** [comment]
The RBS looks like it is running correctly.  Look on the KB Server in the openmake.war/kb/build machines/queue directory.  Run:

find . -name "*.queued" -print

And let me know if you are seeing a lot of files for the RBS that is having issues.

**Comment by r1ddl3m37h15** [comment]
Nothing. Reran with -type -f. Don't have much running.


harvest@prdcikb02:/opt/om/kbserver/tomcat/webapps/openmake.ear/openmake.war/kb/build machines$ find . -type f
./agents/prdcikb02.xml
./agents/6012J02.xml
./agents/09000-MJDWFL1.xml
./agents/5Y61M02.xml
./agents/GDWWTZ1.xml
./agents/DEVCIAGENT02.xml
./agents/PRDCIAGENT01.xml
./agents/DEVCIAGENT01.xml
./devciagent01.xml
./prdcikb02.xml
./devciagent02.xml
./agentsthreshold/09030-LKCGDXW.xml
./agentsthreshold/09030-CK4YCD1.xml
./agentsthreshold/prdcikb02.xml
./agentsthreshold/6012J02.xml
./agentsthreshold/09060-MJCADD0.xml
./agentsthreshold/09060-MJCALC8.xml
./agentsthreshold/09000-MJDWFL1.xml
./agentsthreshold/5Y61M02.xml
./agentsthreshold/GDWWTZ1.xml
./agentsthreshold/DEVCIAGENT02.xml
./agentsthreshold/PRDCIAGENT01.xml
./agentsthreshold/DEVCIAGENT01.xml
./agentsthreshold/09030-MJCADB6.xml
./prdciagent01.xml
harvest@prdcikb02:/opt/om/kbserver/tomcat/webapps/openmake.ear/openmake.war/kb/build machines$

**Comment by r1ddl3m37h15** [comment]
i started a webex https://erieinsurance.webex.com/meet/jeffrey.suess

if i see you join, i'll start the phone part too

**Comment by sbtaylor15** [comment]
On a call right now.  Should be off in a few minutes.

Thanks, Steve

Steve Taylor
CITA and Co-Founder / OpenMake Software / tel: + 1.505.424.6439 x114 / mob:
+1.505.920.6106

Follow us on: Blog <https://www.openmakesoftware.com/insights/> / Twitter
<http://www.twitter.com/openmake>/ Facebook
<https://www.facebook.com/pages/OpenMake-Software/478045172208305> /
LinkedIn <https://www.linkedin.com/in/steve-taylor-b539205> / YouTube
<https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ>/ Google+
<https://plus.google.com/u/0/+Openmakesoftware>

*Winners of the Jolt Award in Change and Configuration Management*

**Comment by r1ddl3m37h15** [comment]
Thanks again for the help!
