### ISSUE TITLE
"FATAL: no pg_hba.conf entry for host"

### ISSUE THREAD

**Issue by meliske** [OpenMake-Software/Meister#10]
On behalf of Jimmy Hurst, AAFES:

There was a server outage last night. All applications were affected. Harvest has successfully restarted, and the Openmake KB service appears to have started but builds generated by Harvest are not reaching the remote build servers. KB server has been rebooted. This did not help. 

ServerOut.log says: 

FATAL: no pg_hba.conf entry for host "192.168.178.192", user "postgres", database "postgres", SSL off 
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "192.168.178.192", user "postgres", database "postgres", SSL off 
at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:291) 
... 

Stopping and restarting Postgres database service on KB server did not resolve the problem.

Urgent help is needed to get Openmake working again.

**Comment by sbtaylor15** [comment]
It sounds like the KB Server is not starting all the way.  Please send us the pg_hba.conf.  It should be under the Postgres Install directory.  We need to add the server ip to that file.

**Comment by meliske** [comment]
Thanks for the quick response.  Will do.



Thanks 😊



*Melinda Skelton*
Sr Principal Support Engineer

Broadcom, Inc

5465 Legacy Drive Suite 700 | Plano, TX 75024-3106
Office: +11240 | melinda.skelton@broadcom.com







*From:* Steve Taylor <notifications@github.com>
*Sent:* Thursday, February 7, 2019 11:25 AM
*To:* OpenMake-Software/Meister <Meister@noreply.github.com>
*Cc:* meliske <Melinda.Skelton@ca.com>; Author <author@noreply.github.com>
*Subject:* Re: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



*CAUTION: This email originated from outside of Broadcom. Do not click
links or open attachments unless you recognize the sender and know the
content is safe.*

It sounds like the KB Server is not starting all the way. Please send us
the pg_hba.conf. It should be under the Postgres Install directory. We need
to add the server ip to that file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_issues_10-23issuecomment-2D461520361&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=QtuCKid0cwSJc6g9DiR8p7Ea_Yd-WEAVx7YL4P8YZQo&s=d1AL61VvRG4gV2tNqRQq3Uhpf4a9GMRrF2JAs0QsBq4&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AafmrczTVeO-5FVA8b5uJLJy9PTWI46j1Vks5vLGF1gaJpZM4anxfo&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=QtuCKid0cwSJc6g9DiR8p7Ea_Yd-WEAVx7YL4P8YZQo&s=h-cJTVHiiHkvZcSfYcYtTI9y6GjzND1dmkwuQdKIIws&e=>
.[image: Image removed by sender.]

**Comment by meliske** [comment]
See attached:

[pg_hba.conf.txt](https://github.com/OpenMake-Software/Meister/files/2842084/pg_hba.conf.txt)

**Comment by sbtaylor15** [comment]
[pg_hba.conf.txt](https://github.com/OpenMake-Software/Meister/files/2842137/pg_hba.conf.txt)

Try this update.  It should allow that address to connect.  Put the updated pg_hba.conf in place and restart the Postgres Service.

**Comment by meliske** [comment]
Thanks!! He’s trying it now.



Any clue why this has been working fine and then all of a sudden the
problem crops up last night?

Noticed he has his loopback address in there.  Possibly something changed
with DNS???



Let me know what you think.



Thanks 😊



*Melinda Skelton*
Sr Principal Support Engineer

Broadcom, Inc

5465 Legacy Drive Suite 700 | Plano, TX 75024-3106
Office: +11240 | melinda.skelton@broadcom.com







*From:* Steve Taylor <notifications@github.com>
*Sent:* Thursday, February 7, 2019 12:09 PM
*To:* OpenMake-Software/Meister <Meister@noreply.github.com>
*Cc:* meliske <Melinda.Skelton@ca.com>; Author <author@noreply.github.com>
*Subject:* Re: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



*CAUTION: This email originated from outside of Broadcom. Do not click
links or open attachments unless you recognize the sender and know the
content is safe.*

pg_hba.conf.txt
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_files_2842137_pg-5Fhba.conf.txt&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=zsYnhUPU6lIQbdKXdrf-kVw47P9ToUH8Opq4haYdwUY&s=kntK50N6ScuRQoHoge689S2HO5cOIUF6mC8f27MxBlw&e=>

Try this update. It should allow that address to connect. Put the updated
pg_hba.conf in place and restart the Postgres Service.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_issues_10-23issuecomment-2D461536037&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=zsYnhUPU6lIQbdKXdrf-kVw47P9ToUH8Opq4haYdwUY&s=Z0BjdUZuwdmdDsZAVJedOIyB6aQPJdX2kwMHXnfBtM4&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AafmrVivcWwYTOfqaIfcddnNIAMs1celks5vLGvOgaJpZM4anxfo&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=zsYnhUPU6lIQbdKXdrf-kVw47P9ToUH8Opq4haYdwUY&s=sfwB6nnJsrVjB7P916NPgWUWANBO0XHglCwVqxFmHtI&e=>
.[image: Image removed by sender.]

**Comment by sbtaylor15** [comment]
Looks like something in the reboot caused the IP to change.

**Comment by meliske** [comment]
Possibly – if it’s on DHCP, and not a static address, it very well could
have changed and DNS hasn’t caught up yet.



Jimmy says that Postgres got hung and would not start.  Would the next
option be to try the IP address that was in the original error message?
"192.168.178.192"



/32 after it?  Or /0 maybe?



Let me know what you think.



Thanks 😊





*From:* Steve Taylor <notifications@github.com>
*Sent:* Thursday, February 7, 2019 12:16 PM
*To:* OpenMake-Software/Meister <Meister@noreply.github.com>
*Cc:* meliske <Melinda.Skelton@ca.com>; Author <author@noreply.github.com>
*Subject:* Re: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



*CAUTION: This email originated from outside of Broadcom. Do not click
links or open attachments unless you recognize the sender and know the
content is safe.*

Looks like something in the reboot caused the IP to change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_issues_10-23issuecomment-2D461538422&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=s95KjgQgBz6jOJ2-5AbzAeuy-InCkvyGcFic7WqUrQk&s=-0RNrSlsAej2RFz14r91UBeduPwagDvN7q-zsBYdRcQ&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AafmrT-2DXfY0NNtlc4SZj2MfbbMVsB1pZks5vLG1ugaJpZM4anxfo&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=s95KjgQgBz6jOJ2-5AbzAeuy-InCkvyGcFic7WqUrQk&s=REets7ccw6JKKhZrOgPv7c1mYV9BppVSdh5VLFyLpLU&e=>
.[image: Image removed by sender.]

**Comment by meliske** [comment]
Looks like second try to start postgres with 0.0.0.0/0 was successful.
He’s trying the KB server now.



Thanks 😊



*From:* Melinda Skelton <melinda.skelton@broadcom.com>
*Sent:* Thursday, February 7, 2019 12:22 PM
*To:* 'OpenMake-Software/Meister' <
reply@reply.github.com>;
'OpenMake-Software/Meister' <Meister@noreply.github.com>
*Cc:* 'meliske' <Melinda.Skelton@ca.com>; 'Author' <
author@noreply.github.com>
*Subject:* RE: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



Possibly – if it’s on DHCP, and not a static address, it very well could
have changed and DNS hasn’t caught up yet.



Jimmy says that Postgres got hung and would not start.  Would the next
option be to try the IP address that was in the original error message?
"192.168.178.192"



/32 after it?  Or /0 maybe?



Let me know what you think.



Thanks 😊





*From:* Steve Taylor <notifications@github.com>
*Sent:* Thursday, February 7, 2019 12:16 PM
*To:* OpenMake-Software/Meister <Meister@noreply.github.com>
*Cc:* meliske <Melinda.Skelton@ca.com>; Author <author@noreply.github.com>
*Subject:* Re: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



*CAUTION: This email originated from outside of Broadcom. Do not click
links or open attachments unless you recognize the sender and know the
content is safe.*

Looks like something in the reboot caused the IP to change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_issues_10-23issuecomment-2D461538422&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=s95KjgQgBz6jOJ2-5AbzAeuy-InCkvyGcFic7WqUrQk&s=-0RNrSlsAej2RFz14r91UBeduPwagDvN7q-zsBYdRcQ&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AafmrT-2DXfY0NNtlc4SZj2MfbbMVsB1pZks5vLG1ugaJpZM4anxfo&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=s95KjgQgBz6jOJ2-5AbzAeuy-InCkvyGcFic7WqUrQk&s=REets7ccw6JKKhZrOgPv7c1mYV9BppVSdh5VLFyLpLU&e=>
.[image: Image removed by sender.]

**Comment by meliske** [comment]
Jimmy’s response after restarting KB server:





I’ve restarted that successfully too. I’m also restarting our 3 main remote
agent services..I also noticed the server.out file only contains 1 line
now..



* Thu Feb 07 12:21:06 CST 2019 : Rebuilt Administrators Group



So maybe the error message hadn’t come up before.. J



Which log files do we need.



If this is what we suspect, should I have him try to ping the agent
machines from the KB server to see if they can connect and respond with the
right IP addresss?



Thanks 😊



*From:* Steve Taylor <notifications@github.com>
*Sent:* Thursday, February 7, 2019 12:09 PM
*To:* OpenMake-Software/Meister <Meister@noreply.github.com>
*Cc:* meliske <Melinda.Skelton@ca.com>; Author <author@noreply.github.com>
*Subject:* Re: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



*CAUTION: This email originated from outside of Broadcom. Do not click
links or open attachments unless you recognize the sender and know the
content is safe.*

pg_hba.conf.txt
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_files_2842137_pg-5Fhba.conf.txt&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=zsYnhUPU6lIQbdKXdrf-kVw47P9ToUH8Opq4haYdwUY&s=kntK50N6ScuRQoHoge689S2HO5cOIUF6mC8f27MxBlw&e=>

Try this update. It should allow that address to connect. Put the updated
pg_hba.conf in place and restart the Postgres Service.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_issues_10-23issuecomment-2D461536037&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=zsYnhUPU6lIQbdKXdrf-kVw47P9ToUH8Opq4haYdwUY&s=Z0BjdUZuwdmdDsZAVJedOIyB6aQPJdX2kwMHXnfBtM4&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AafmrVivcWwYTOfqaIfcddnNIAMs1celks5vLGvOgaJpZM4anxfo&d=DwMCaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=zsYnhUPU6lIQbdKXdrf-kVw47P9ToUH8Opq4haYdwUY&s=sfwB6nnJsrVjB7P916NPgWUWANBO0XHglCwVqxFmHtI&e=>
.[image: Image removed by sender.]

**Comment by sbtaylor15** [comment]
Put in both the loopback and any address and let's see if Postgres starts up correctly.

```
# IPv4 local connections:
host    all         all         127.0.0.1/32          md5
host    all         all         0.0.0.0/0             md5
# IPv6 local connections:
host    all         all         ::1/128               md5
```

**Comment by meliske** [comment]
Will give it a try.



Thanks 😊



*From:* Steve Taylor <notifications@github.com>
*Sent:* Thursday, February 7, 2019 12:31 PM
*To:* OpenMake-Software/Meister <Meister@noreply.github.com>
*Cc:* meliske <Melinda.Skelton@ca.com>; Author <author@noreply.github.com>
*Subject:* Re: [OpenMake-Software/Meister] "FATAL: no pg_hba.conf entry for
host" (#10)



*CAUTION: This email originated from outside of Broadcom. Do not click
links or open attachments unless you recognize the sender and know the
content is safe.*

Put in both the loopback and any address and let's see if Postgres starts
up correctly.
IPv4 local connections:

host all all 127.0.0.1/32
<https://urldefense.proofpoint.com/v2/url?u=http-3A__127.0.0.1_32&d=DwQFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=Oq9pSxc8h8XDimB4hGNhf1iwApgLw23XXPuSoH8QddM&s=EB-QrViFn6K7A9-7K7xsqB6qT03RV8bT8E8elC3sUIk&e=>
md5
host all all 0.0.0.0/0
<https://urldefense.proofpoint.com/v2/url?u=http-3A__0.0.0.0_0&d=DwQFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=Oq9pSxc8h8XDimB4hGNhf1iwApgLw23XXPuSoH8QddM&s=s73okZ6J0Pn0gkjYmtj5Ker-7aSliwY5DyaMHgaKCUQ&e=>
md5
IPv6 local connections:

host all all ::1/128 md5

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMake-2DSoftware_Meister_issues_10-23issuecomment-2D461543643&d=DwMFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=Oq9pSxc8h8XDimB4hGNhf1iwApgLw23XXPuSoH8QddM&s=DUEgiHhIF3JHlNYaz4kdl5AgbQNQDkxUvYrEDKnGhXM&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AafmrSUcw3tQkEJOgEIzbQKd0KG1kACOks5vLHDlgaJpZM4anxfo&d=DwMFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=yiGyVdE1Mnr5bl36UdjAqcFpn1xvwaTNkLMo508Xu7c&m=Oq9pSxc8h8XDimB4hGNhf1iwApgLw23XXPuSoH8QddM&s=3TLvueH7bBKxDLQO7bQ9h3AVi8w85DF_2GH1BoIatj0&e=>
.[image: Image removed by sender.]

**Comment by meliske** [comment]
I heard from the customer that this is resolved.  Aside from the Postgres error we were seeing there was a networking problem that was preventing build requests from Harvest from reaching the Openmake KB server.  That's now corrected so Openmake is working normally now.  Thanks so much for your help :)
