### ISSUE TITLE
After upgrading from to OM 7 system ask to register when clieck to help

### ISSUE THREAD

**Issue by AntonioArenas** [OpenMake-Software/Meister#12]
Hi guys.

After upgrading our OM and add the license key, the system logins properly but if I go into Help, Openmake Registration the register popup displays. 

![image](https://user-images.githubusercontent.com/24460316/56680959-4b8a6780-6696-11e9-97aa-5f4f3c19b4b5.png)

Are we supposed to register our product online or something? in addition to entering the product key?

Also, on the old system, I have to login everytime I start the GUI. 
On this system, it doesn't ask me to login.

Please guide me here.

Thanks

**Comment by sbtaylor15** [comment]
The KB Server is probably not starting up all the way.  Please send us the KB Server log files <install>/kbserver/tomcat/webapps/openmake.ear/logs/*.log files.

**Comment by AntonioArenas** [comment]
Thanks for your feedback Steve.

Just rebooted and it comes up to this page when I start DDS

![image_3](https://user-images.githubusercontent.com/24460316/56685747-a4f79400-66a0-11e9-9d92-6e88a3ed3ade.png)


If I click on Help - Openmake Registration - I get this 
![image_4](https://user-images.githubusercontent.com/24460316/56685792-be98db80-66a0-11e9-941d-9d01c3f4dbd5.png)
 

I have these log files from yesterday afternoon --  not sure when or why then and not now ..
![image_5](https://user-images.githubusercontent.com/24460316/56685840-d6705f80-66a0-11e9-91d1-f205fdfaa504.png)

 

I've attached the 2 that had data
[ServerStartup.log](https://github.com/OpenMake-Software/Meister/files/3113788/ServerStartup.log)
[ServerOut.log](https://github.com/OpenMake-Software/Meister/files/3113789/ServerOut.log)

Let me know your thoughts.
Thanks

**Comment by sbtaylor15** [comment]
Enter the following in Windows Explorer address bar:  %APPDATA%\data and hit enter.  In that directory, there is the omenvironment.properties file.  Edit that file and verify that OPENMAKE_SERVER value is pointing to the correct KB Server and Port

**Comment by AntonioArenas** [comment]
Hi Steve.

At the end, we uninstall OM 7 KB Server windows service and reinstall it

We have an Error which says - The LoadLibrary function failed for the following reason: LoadLibrary is not a valid Win32 application
The second Error says - Could not load the Java Virtual Machine 

So we install java 32 bit and it looks like everything is OK.

Now we want to make sure if everything is working properly, so which are all the logs that i must review in order to check that?

Another thing, I installed the same version 32bit Java that I had installed as 64bit, 
it told me that my version 1.8.0_192 was outdated and should be upgraded. 
Of the currently available versions, is OM planning on updating to 1.8.0_211 or 212? 

Thanks in advance!

**Comment by sbtaylor15** [comment]
You will need to use the latest 7.5.1 64bit installer.  It will support up to 1.8.0_300 64bit Java.  Here is the link to the installer:  [meister-751-win32-64.zip](https://www.openmakesoftware.com/meister751/meister-751-win32-64.zip)

**Comment by AntonioArenas** [comment]
Thanks Steve.

But outside of:
/kbserver/tomcat/webapps/openmake.ear/logs/*.log files.

Are there any other logs in order to check if everything is working properly?

**Comment by sbtaylor15** [comment]
Access the following url:. http://(kbserver):58080/openmake/InitServer

Should return details about the license and kb server details.

**Comment by AntonioArenas** [comment]
Thanks

Previously we received this file updated_meister-751-win32-64.zip it looks like the same, can you confirm if meister-751-win32-64.zip supports 1.8.0_300 64bit Java.. i ask you since the documentation mention that it only goes up to java 1.8.0_200.

Can we get a definitive answer as to whether Openmake KB will run in a totally 64bit environment? 

Thank you

**Comment by sbtaylor15** [comment]
Yes, using the latest installer I provided will enable you to run in 64bit environment.

**Comment by AntonioArenas** [comment]
And it will suppports supports 1.8.0_300 64bit Java...i ask you since the documentation mention that it only goes up to java 1.8.0_200.

**Comment by sbtaylor15** [comment]
I double checked the code and its up to 1.8.0_300.
