### ISSUE TITLE
Command line returns error level 8 when using the -SYNC option

### ISSUE THREAD

**Issue by teabuilder** [OpenMake-Software/Meister#14]
We are attempting to call Meister using a command line from Jenkins to execute the build process. We have successfully implement the process but when we use the -SYNC option it always returns a value of 8 when checking the errorlevel. We need the errorlevel to tell Jenkins when a build fails >0 or is successful=0.  Without the -SYNC errorlevel always returns 0 even if the build fails.

Example of a build command line:
java -cp C:\OM\client\bin\omcmdline.jar com.openmake.cmdline.Main -SYNC -build srs17CmdLine [BuildVersion=6.2.0.0,BuildPreviousVersion=6.1.0.0]
echo errorlevel=%errorlevel%

Our Meister build project activities are all defined as command line executions calling nant or DOS commands.

**Comment by sbtaylor15** [comment]
Can you send us the log output when using -SYNC?  Also, without -SYNC it will always return 0 since the workflow has been submitted to the RBS for background processing.

**Comment by teabuilder** [comment]
The zip file contains the logs from the KB server along with the cmd file, the workflow xml, and the cmd log.

[CmdLineTest.zip](https://github.com/OpenMake-Software/Meister/files/3218143/CmdLineTest.zip)

**Comment by sbtaylor15** [comment]
Looks like a parsing error is happening that is causing the omcmdline.jar to think the workflow failed when it was a success.  We are in the process of debugging this issue.

**Comment by teabuilder** [comment]
While you are looking please see if you can figure out why it doesn’t abide by the dependency definitions for multiple activities in a workflow when executing from the command line. This may be related and is not critical but it would be nice if it worked.

Thanks,
Jerry Norman
Office of Information Technology Services | Builder<https://texasedu.sharepoint.com/sites/its/app/dev/build/default.aspx>
Texas Education Agency
(512) 463-8047

**Comment by sbtaylor15** [comment]
What version of the Meister client are you running when you use the omcmdline.jar to run a command line workflow?

**Comment by teabuilder** [comment]
OpenMake Dynamic DevOps Suite
Version: 7.5

**Comment by teabuilder** [comment]
Any progress on this issue?

**Comment by sbtaylor15** [comment]
Make a backup of <install>/miester/client/bin/*.jar on the machine that is executing the omcmdline.jar command.  Then replace the jars with the ones from the attached zip file.  Let use know the results when running with -SYNC.
[omclient.zip](https://github.com/OpenMake-Software/Meister/files/3266633/omclient.zip)

**Comment by teabuilder** [comment]
The fix resolved the -SYNC issue. Thank you for your timely response and fix.
