### ISSUE TITLE
Need Point of contact to update license file, xxx org

### ISSUE THREAD

**Issue by nmahapatro** [OpenMake-Software/Meister#2]
comment 1

**Comment by sbtaylor15** [comment]
I can take care of that.  Please send me your existing license so I can
update it.

Thanks Steve

**Comment by MAH6146** [comment]
Hi Steve,

I am quite new to meister, please guide in adding new license. We want to connect to below KB server as Remote Agents.

I got the current license file from below directory. Please see attached. Let me know what details do I need to share with you.
\\ntapth3769m00\D-root\Program Files (x86)\Meister\kbserver\tomcat\webapps\openmake.ear\openmake.war\license

Thanks,
Nigam

**Comment by sbtaylor15** [comment]
The license fie was correct.  Just the dns resolution was not working from client machines.  Using the ip address solved the issues.

**Comment by MAH6146** [comment]
Removing contents due to security issue.
