### ISSUE TITLE
Deleting posts due to some issue

### ISSUE THREAD

**Issue by KR-SHASTRI** [OpenMake-Software/Meister#3]
Comment 1

**Comment by sbtaylor15** [comment]
Please stop and restart the KB Server processes and then send us the <install>/kbserver/tomcat/webapps/openmake.ear/logs/*.log files.

Thanks, Steve

**Comment by sha9963** [comment]
Hi Steve ,
Please find the below attached Log files and suggest.
[ServerStartup.log](https://github.com/OpenMake-Software/Meister/files/1531882/ServerStartup.log)

[ServerOut.log](https://github.com/OpenMake-Software/Meister/files/1531883/ServerOut.log)

Thanks, Sachin

**Comment by sbtaylor15** [comment]
Looks like you have 0 byte workflow that maybe causing issues.

Delete the following file if its 0 bytes and restart the KB Server:

D:\Program Files (x86)\Meister\kbserver\tomcat\webapps\openmake.ear\openmake.war\kb\jobs\public\Run CI Check On NTAPTH3769M00.xml


After the restart send us the output from:

http://<kbserver>:58080/openmake/InitServer

Thanks, Steve

**Comment by sha9963** [comment]
Hi Steve ,
 Please find the below attached Log files and suggest.
[ServerStartup.log](https://github.com/OpenMake-Software/Meister/files/1532142/ServerStartup.log)

[ServerOut.log](https://github.com/OpenMake-Software/Meister/files/1532143/ServerOut.log)

Thanks, Sachin

**Comment by sbtaylor15** [comment]
The KB Server looks like it started up without errors.

RDP into the KB Server and hit the following URL and send us the output:
     http://localhost:58080/openmake/InitServer

**Comment by sha9963** [comment]
Hi Steve ,
Please find attached file.
[openmake_InitServer_output.txt](https://github.com/OpenMake-Software/Meister/files/1532215/openmake_InitServer_output.txt)

Thanks ,Sachin

**Comment by sbtaylor15** [comment]
So the KB Server is up and running and accessible from local host.

Hit http://NTAPTH3769M00:58080/openmake/InitServer from the RDP session and then from another machine.  If you get "page not found" or similar then we have a firewall issue that needs to be sorted out.  If it does work then try using the Meister GUI to connect to the KB Server.

Thanks, Steve

**Comment by sha9963** [comment]
Hi Steve ,
While trying to connect to Meister GUI I'm getting errors which is attached.
Also please find the Log file which is generated in my local system.
![dds install validation error](https://user-images.githubusercontent.com/34278131/33673447-56790018-da72-11e7-963d-04f2d0ae74e4.PNG)
[log.txt](https://github.com/OpenMake-Software/Meister/files/1535982/log.txt)

**Comment by sbtaylor15** [comment]
From the machine getting the Meister GUI error, open a browser and hit:

http://ntapth3769m00:58080/openmake/InitServer

send me the results.

Thanks, Steve

**Comment by sha9963** [comment]
Hi Steve ,

Please find attached file.
[Browser Result.txt](https://github.com/OpenMake-Software/Meister/files/1536154/Browser.Result.txt)

Thanks, Sachin

**Comment by sha9963** [comment]
Hi Steve ,

Please assist with further steps that I should follow to resolve this issue.

Thanks & Regards,
Sachin

**Comment by sbtaylor15** [comment]
Lets setup a web meeting to get this resolved.  Do you have time today?

**Comment by sha9963** [comment]
Sure Steve.

Where do I send you meeting invitation? Or you are going to send me a meeting invite ?

Thanks, Sachin

**Comment by sbtaylor15** [comment]
sent the invite to steve.taylor@openmakesoftware.com

**Comment by sha9963** [comment]
Hi Steve ,
My apologies but at this point of time I won't be able to send you a web meeting invite on steve.taylor@openmakesoftware.com . I'll talk with my superiors on the alternatives available for web meetings outside the organization and will communicate.

Thanks , Sachin

**Comment by sbtaylor15** [comment]
Ok, we use join.me or webex and give you screen sharing role so we can see whats happening on your machine.

Thanks, Steve

**Comment by sha9963** [comment]
Hi Steve ,

Blocked sometime for Web meeting today from 9:00-10:00 AM CST.
Sent the meeting invite at above-said e-mail id.

Regards,
Sachin

**Comment by sha9963** [comment]
Hi Steve ,
Do let me know your availability when we can schedule this meeting.
My apologies for not checking with you prior to scheduling this meeting.

Thanks, Sachin

**Comment by sbtaylor15** [comment]
I can do this afternoon after 2 CST.

Thanks, Steve

Steve Taylor
CITA and Co-Founder / OpenMake Software / tel: + 1.505.424.6439 x114 / mob:
+1.505.920.6106

Follow us on: Blog <https://www.openmakesoftware.com/insights/> / Twitter
<http://www.twitter.com/openmake>/ Facebook
<https://www.facebook.com/pages/OpenMake-Software/478045172208305> /
LinkedIn <https://www.linkedin.com/in/steve-taylor-b539205> / YouTube
<https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ>/ Google+
<https://plus.google.com/u/0/+Openmakesoftware>

*Winners of the Jolt Award in Change and Configuration Management*

**Comment by sha9963** [comment]
Hi Steve,
I am from offshore location(India); can you please let me know your availability before 1 PM CST so that we can set up web meeting and figure out the issue.
Regards, Sachin

**Comment by sbtaylor15** [comment]
Can you email me a web invite?  I am available now.

Thanks, Steve

**Comment by sha9963** [comment]
Hi Steve ,

Blocked sometime for Web meeting today from 11:30-12:30 AM CST.
Sent the meeting invite at above-said e-mail id.

Regards,  Sachin

**Comment by sbtaylor15** [comment]
Found that the user count was exceeded throwing an error.

**Comment by sha9963** [comment]
Thanks Steve.

I was about to close this issue; we really had an informative and fruitful session wherein we found the root cause of why the error was happening.
Hope to get more informative sessions in future.

Thanks & Regards,
Sachin
