### ISSUE TITLE
Unable to setup Remote Agent

### ISSUE THREAD

**Issue by JGNanjappan** [OpenMake-Software/Meister#5]
Hi Team,
could you please help me to add the remote agent.., as i could find the option is not enabled to add the remote agent.
as i am getting an error 
"An error occurred while attempting to execute the workflow, testing1:Fatal errors occurred while submitting a build to the remote agent, ***
unable to run the worflow since the server pool *** has no remote agents defined to it."
please let us know for further details.
Thanks 
Jagadesh

**Comment by JGNanjappan** [comment]
[openmake_1.docx](https://github.com/OpenMake-Software/Meister/files/1879987/openmake_1.docx)

**Comment by sbtaylor15** [comment]
The Remote Build Server is not registering itself with the KB Server.   The bottom pane in the Server Pool Administration should list the available build servers.  View the build server logs which are in <install>/client/buildserver/logs directory for any errors.

**Comment by JGNanjappan** [comment]
please find the attached log files
[RemoteBuildOut.log](https://github.com/OpenMake-Software/Meister/files/1880053/RemoteBuildOut.log)
[RemoteBuildErr.log](https://github.com/OpenMake-Software/Meister/files/1880054/RemoteBuildErr.log)
[RemoteBuildStartup.log](https://github.com/OpenMake-Software/Meister/files/1880055/RemoteBuildStartup.log)

**Comment by JGNanjappan** [comment]
My add agent to pool is disabled, how to enable the same.

**Comment by sbtaylor15** [comment]
On the RBS, edit the<install>/client/buildserver/rbs_startup.xml.  Find the localmode parameter and change it from true to false.  Then restart the RBS.  Once restarted, the build server should show up in the Agent list in the web UI.

**Comment by JGNanjappan** [comment]
i have followed the instruction but still no luck., i have attached the logfiles for your reference, could you please help me with, please let me know for further details 
[openmake.docx](https://github.com/OpenMake-Software/Meister/files/1884523/openmake.docx)

**Comment by sbtaylor15** [comment]
Can you send me a zip of your <kbs install>/kbserver/tomcat/webapps/openmake.ear/openmake.war/kb/build machines?

Also, from your Remote Build Server, <install>/client/buildserver/rbs_startup.xml

Finally, the output from the following URL in a browser:  http://<kb server>:58080/openmake/InitServer

Thanks, Steve

**Comment by JGNanjappan** [comment]
Hi Steve,

Sorry for the delay., please find the attachment., now i could see the agent pool is enabled, could you please clarify - can we have two build servers one for Windows and the other one for Linux?
so that for Linux servers - i can directly create a workflow to execute the linux commands in linux servers.
could you please help me with this.

[buildserver.zip](https://github.com/OpenMake-Software/Meister/files/1899465/buildserver.zip)
[build machines.zip](https://github.com/OpenMake-Software/Meister/files/1899466/build.machines.zip)
[openmake.docx](https://github.com/OpenMake-Software/Meister/files/1899467/openmake.docx)

thanks 
Jagadesh

**Comment by sbtaylor15** [comment]
Hi Jagadesh,

Looks like the Remote Build Server is not starting up since one is already running.  Can you kill the java and JNT processes on the Remote Build Server and then start the Remote Build Server again.  The log files in the install/client/buildserver/logs/*.log should have no errors in them. 

As for the Linux and Windows build servers, you would create a server pool for each one and add in the appropriate servers in to the pool.  From there in the Workflow Editor you would select which Server pool to run the commands on.  

What timezone are you in?

Thanks, Steve

**Comment by JGNanjappan** [comment]
Hi Steve,

I am in IST (India Standard Time) UTC/GMT +5:30 hours

[RemoteBuildOut.log](https://github.com/OpenMake-Software/Meister/files/1903533/RemoteBuildOut.log)
[RemoteBuildStartup.log](https://github.com/OpenMake-Software/Meister/files/1903534/RemoteBuildStartup.log)

Much appreciated if you could join a Skype session, so that i can send an invite on your available time.

**Comment by sbtaylor15** [comment]
Hi Jagadesh,

Can you send me your Skype info and email to steve@deployhub.com so I can send you the invite?  Monday or Tuesday at 11:00 am MST work?  Not sure which shift you are working.

Thanks, Steve

**Comment by JGNanjappan** [comment]
Hi Steve,

I have started the Skype call., and I am already in. Do you face any difficulties in joining the same ?
