### ISSUE TITLE
Meister  web interface not running on PC. 

### ISSUE THREAD

**Issue by javeden** [OpenMake-Software/Meister#6]
We use Meister 7.2. I have not run it in a while, but now the web interface will not run on my PCThe web interface throws the following error:

Java Plug-in 1.6.0_45
Using JRE version 1.6.0_45-b06 Java HotSpot(TM) Client VM
User home directory = C:\Users\ca610

----------------------------------------------------
c:   clear console window
f:   finalize objects on finalization queue
g:   garbage collect
h:   display this help message
l:   dump classloader list
m:   print memory usage
o:   trigger logging
p:   reload proxy configuration
q:   hide console
r:   reload policy configuration
s:   dump system and deployment properties
t:   dump thread list
v:   dump thread stack
x:   clear classloader cache
0-5: set trace level to <n>
----------------------------------------------------

Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\236488d7-1617874c-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\7be13698-591d1a77-0.9.7.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\5d863498-39cddcdc-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\4747f796-2a6edd4a-0.1.0.4-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\12\6b67b64c-4d8feda1-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\638d4b35-400ab1ab-7.2.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\3e812d23-42ff4e74-6.4.0.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\60\9788d7c-41b369f6-6.4.1.14-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\12\6b67b64c-4d8feda1-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\12\6b67b64c-4d8feda1-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\12\6b67b64c-4d8feda1-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\6\6eab5346-2d9d2a02.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\8\31879508-11da8141-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\10\2868ce8a-1ed23134.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\12\6b67b64c-4d8feda1-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\14\402210ce-630a705f.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\3e812d23-42ff4e74-6.4.0.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\3e812d23-42ff4e74-6.4.0.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\19\64f7ef13-70dab336.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\4747f796-2a6edd4a-0.1.0.4-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\70ede416-4a285076-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\236488d7-1617874c-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\7a7de1d7-77e034e8.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\4946e298-32a47ce0-0.9.3.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\5d863498-39cddcdc-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\7be13698-591d1a77-0.9.7.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\26\7a44e9a-57a438d8.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\27\3eeff31b-62965e4a-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\3e812d23-42ff4e74-6.4.0.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\d56fbe3-2d94b56d.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\37\491d75e5-6c444ed9.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\38\1d2a6e66-3a1de47b.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\39\3454a727-20f1dd51.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\44\27514f2c-27e8db29-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\51\126f5b33-4d84c311-6.3.0.2-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\52\1ff66534-16a1e396-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\267d5eb5-1039ac1c.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\638d4b35-400ab1ab-7.2.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\58\458458ba-27712ba8.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\60\9788d7c-41b369f6-6.4.1.14-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\63\1c05efbf-1da430a5.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\3e812d23-42ff4e74-6.4.0.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\4747f796-2a6edd4a-0.1.0.4-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\4747f796-2a6edd4a-0.1.0.4-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\4747f796-2a6edd4a-0.1.0.4-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\7be13698-591d1a77-0.9.7.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\7be13698-591d1a77-0.9.7.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\7be13698-591d1a77-0.9.7.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\60\9788d7c-41b369f6-6.4.1.14-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\60\9788d7c-41b369f6-6.4.1.14-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\60\9788d7c-41b369f6-6.4.1.14-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\638d4b35-400ab1ab-7.2.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\638d4b35-400ab1ab-7.2.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\638d4b35-400ab1ab-7.2.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\236488d7-1617874c-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\236488d7-1617874c-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\236488d7-1617874c-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\5d863498-39cddcdc-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\5d863498-39cddcdc-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\5d863498-39cddcdc-1.1.1.1-.idx
load: class com.openmake.client.OMApplet not found.
java.lang.ClassNotFoundException: com.openmake.client.OMApplet
	at sun.applet.AppletClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadCode(Unknown Source)
	at sun.applet.AppletPanel.createApplet(Unknown Source)
	at sun.plugin.AppletViewer.createApplet(Unknown Source)
	at sun.applet.AppletPanel.runLoader(Unknown Source)
	at sun.applet.AppletPanel.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\23\236488d7-1617874c-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\7be13698-591d1a77-0.9.7.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\5d863498-39cddcdc-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\4747f796-2a6edd4a-0.1.0.4-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\12\6b67b64c-4d8feda1-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\53\638d4b35-400ab1ab-7.2.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\35\3e812d23-42ff4e74-6.4.0.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\60\9788d7c-41b369f6-6.4.1.14-.idx
load: class com.openmake.client.OMApplet not found.
java.lang.ClassNotFoundException: com.openmake.client.OMApplet
	at sun.applet.AppletClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadCode(Unknown Source)
	at sun.applet.AppletPanel.createApplet(Unknown Source)
	at sun.plugin.AppletViewer.createApplet(Unknown Source)
	at sun.applet.AppletPanel.runLoader(Unknown Source)
	at sun.applet.AppletPanel.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\70ede416-4a285076-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\4946e298-32a47ce0-0.9.3.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\8\31879508-11da8141-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\44\27514f2c-27e8db29-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\52\1ff66534-16a1e396-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\51\126f5b33-4d84c311-6.3.0.2-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\27\3eeff31b-62965e4a-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\44\27514f2c-27e8db29-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\44\27514f2c-27e8db29-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\44\27514f2c-27e8db29-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\51\126f5b33-4d84c311-6.3.0.2-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\51\126f5b33-4d84c311-6.3.0.2-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\51\126f5b33-4d84c311-6.3.0.2-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\4946e298-32a47ce0-0.9.3.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\4946e298-32a47ce0-0.9.3.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\4946e298-32a47ce0-0.9.3.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\27\3eeff31b-62965e4a-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\27\3eeff31b-62965e4a-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\27\3eeff31b-62965e4a-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\52\1ff66534-16a1e396-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\52\1ff66534-16a1e396-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\52\1ff66534-16a1e396-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\70ede416-4a285076-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\70ede416-4a285076-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\70ede416-4a285076-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\8\31879508-11da8141-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\8\31879508-11da8141-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\8\31879508-11da8141-1.1.1.1-.idx
load: class com.openmake.client.OMApplet not found.
java.lang.ClassNotFoundException: com.openmake.client.OMApplet
	at sun.applet.AppletClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadCode(Unknown Source)
	at sun.applet.AppletPanel.createApplet(Unknown Source)
	at sun.plugin.AppletViewer.createApplet(Unknown Source)
	at sun.applet.AppletPanel.runLoader(Unknown Source)
	at sun.applet.AppletPanel.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\22\70ede416-4a285076-2.4.0.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\24\4946e298-32a47ce0-0.9.3.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\8\31879508-11da8141-1.1.1.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\44\27514f2c-27e8db29-1.2.8.1-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\52\1ff66534-16a1e396-6.3.1.0-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\51\126f5b33-4d84c311-6.3.0.2-.idx
Invalidating entry url= file=C:\Users\ca610\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\27\3eeff31b-62965e4a-6.3.1.0-.idx
load: class com.openmake.client.OMApplet not found.
java.lang.ClassNotFoundException: com.openmake.client.OMApplet
	at sun.applet.AppletClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.applet.AppletClassLoader.loadCode(Unknown Source)
	at sun.applet.AppletPanel.createApplet(Unknown Source)
	at sun.plugin.AppletViewer.createApplet(Unknown Source)
	at sun.applet.AppletPanel.runLoader(Unknown Source)
	at sun.applet.AppletPanel.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by sbtaylor15** [comment]
Looks like the jar cache is missing the Meister jar files.  You will need to clear the jar cache from the Java Plugin manager for the browser and try to reload the UI.

**Comment by sbtaylor15** [comment]
Sent instructions via email on how to edit the XML files on the KB Server since newer versions of Java no longer run applets in the browsers.
