### ISSUE TITLE
QQ question about upgrades. sev 4.

### ISSUE THREAD

**Issue by r1ddl3m37h15** [OpenMake-Software/Meister#7]
Just need the download link. 

KB is RHEL. 2 RBS, both Windows.

**Comment by sbtaylor15** [comment]
Here are the links:

https://www.openmakesoftware.com/meister751/meister-751-win32-64.zip
https://www.openmakesoftware.com/meister751/meister-7.5.1-linux-headless_install.zip

The zip files contain the KBS, RBS and Client.

**Comment by r1ddl3m37h15** [comment]
Thanks!
