### ISSUE TITLE
fyi. dup file on window. sev 4

### ISSUE THREAD

**Issue by r1ddl3m37h15** [OpenMake-Software/Meister#8]
For both of the 7.5.1 zip files the directory .\kbserver\tomcat\webapps\openmake.ear\openmake.war\kb\build types\Windows contains both "COGNOS POWERHOUSE COMPILE.xml" and "Cognos Powerhouse Compile.xml". 

The unzip on windows complains about it.  Just fyi.  This isn't really a problem as the contents are the same.  Feel free to close.

**Comment by sbtaylor15** [comment]
Ok, thanks for the heads up.  Not an issue since the file is identical.
